pipeline {
    agent {
        kubernetes {
            // Usa la plantilla estática definida en Jenkins ("ci-agent")
            inheritFrom 'ci-agent'
            label 'ci-agent'
            defaultContainer 'maven'
        }
    }

    environment {
        // Dentro del workspace el repo se chequea completo,
        // y como el Jenkinsfile está en app/microservice,
        // la ruta relativa es simplemente:
        APP_DIR = 'app/microservice'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                container('maven') {
                    dir("${APP_DIR}") {
                        sh 'mvn -B clean test'
                    }
                }
            }
        }

        stage('Package') {
            steps {
                container('maven') {
                    dir("${APP_DIR}") {
                        sh 'mvn -B package -DskipTests'
                    }
                }
            }
        }
    }
}
